runtime: python310
env: flex
entrypoint: panel serve panel.py --address 0.0.0.0 --port 8080 --allow-websocket-origin="*"

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10